using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.Utils.MVVM.Services;
using System.Data.Entity;

namespace TDU.CMS.Views.CardRequest
{
    [DevExpress.Utils.MVVM.UI.ViewType("CardRequestCollectionView")]
    public partial class CardRequestsView : DevExpress.XtraEditors.XtraUserControl
    {
        public CardRequestsView()
        {
            InitializeComponent();
            InitBindings();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            TDU.CMS.DataBase.CMSDbContext dbContext = new TDU.CMS.DataBase.CMSDbContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.CardRequests.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.CardRequests.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void InitBindings()
        {
            //throw new NotImplementedException();

            var fluentAPI = mvvmContext1.OfType<TDU.CMS.ViewModels.CardRequestCollectionViewModel>();
            fluentAPI.SetBinding(gridView1, gView => gView.LoadingPanelVisible, x => x.IsLoading);
            fluentAPI.SetBinding(gridControl1, gControl => gControl.DataSource, x => x.Entities);

            fluentAPI
                .WithEvent
                <DevExpress.XtraGrid.Views.Base.ColumnView,
                    DevExpress.XtraGrid.Views.Base.FocusedRowObjectChangedEventArgs>(gridView1,
                        "FocusedRowObjectChanged")
                .SetBinding(x => x.SelectedEntity,
                    args => args.Row as Models.CardRequest,
                    (gView, entity) => gView.FocusedRowHandle = gView.FindRow(entity));
        }
    }
}